DROP TABLE IF EXISTS `USERS` CASCADE;
create table USERS
(
    users_id bigint generated by default as identity,
    username varchar(255),
    name varchar(15),
    password varchar(25),
    email varchar(50),
    gender integer,
    phone_number varchar(30),
    nickname varchar(25),
    enabled BOOLEAN,
    primary key (users_id)
)
